[2025-03-09T11:23:01.218+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_storage_task manual__2025-03-09T11:21:17.447286+00:00 [queued]>
[2025-03-09T11:23:01.228+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_storage_task manual__2025-03-09T11:21:17.447286+00:00 [queued]>
[2025-03-09T11:23:01.228+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-09T11:23:01.243+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_storage_task> on 2025-03-09 11:21:17.447286+00:00
[2025-03-09T11:23:01.246+0000] {standard_task_runner.py:57} INFO - Started process 2654 to run task
[2025-03-09T11:23:01.249+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_storage_task', 'manual__2025-03-09T11:21:17.447286+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmp4svyyczq']
[2025-03-09T11:23:01.251+0000] {standard_task_runner.py:85} INFO - Job 318: Subtask data_storage_task
[2025-03-09T11:23:01.271+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-09T11:23:01.310+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_storage_task manual__2025-03-09T11:21:17.447286+00:00 [running]> on host 157237bff8f7
[2025-03-09T11:23:01.418+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_storage_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T11:21:17.447286+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T11:21:17.447286+00:00'
[2025-03-09T11:23:01.419+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-09T11:23:01.420+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/***\n                        dvc pull /opt/***/data/transformed\n                        python /opt/***/executables/data_storage.py && \t\t\tgit add logs &&    \t\t\tgit status &&                         git commit -m "Updated stored data version" -a &&                         dvc push && git push\n                    ']
[2025-03-09T11:23:01.427+0000] {subprocess.py:86} INFO - Output:
[2025-03-09T11:23:05.091+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-09T11:23:06.545+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,544 : INFO : Starting data storage for customer_data.csv
[2025-03-09T11:23:06.545+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,545 : INFO : Connecting to Database
[2025-03-09T11:23:06.571+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,571 : INFO : Connecting to Database Successfull
[2025-03-09T11:23:06.571+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,571 : INFO : Reading insert script template
[2025-03-09T11:23:06.572+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,571 : INFO : Executing script to Database
[2025-03-09T11:23:06.572+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,571 : INFO : Inserting data to database
[2025-03-09T11:23:06.687+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,687 : ERROR : Error storing data: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 6 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)')
[2025-03-09T11:23:06.690+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,690 : INFO : Starting data storage for database_data.csv
[2025-03-09T11:23:06.691+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,690 : INFO : Connecting to Database
[2025-03-09T11:23:06.704+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,704 : INFO : Connecting to Database Successfull
[2025-03-09T11:23:06.705+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,704 : INFO : Reading insert script template
[2025-03-09T11:23:06.705+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,705 : INFO : Executing script to Database
[2025-03-09T11:23:06.705+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:06,705 : INFO : Inserting data to database
[2025-03-09T11:23:13.651+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:13,651 : INFO : Executed script successfully !!
[2025-03-09T11:23:13.652+0000] {subprocess.py:93} INFO - 2025-03-09 11:23:13,652 : INFO : Connection closed !!
[2025-03-09T11:23:13.893+0000] {subprocess.py:93} INFO - On branch main
[2025-03-09T11:23:13.893+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-09T11:23:13.893+0000] {subprocess.py:93} INFO - 
[2025-03-09T11:23:13.894+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-09T11:23:13.894+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-09T11:23:13.894+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T11:21:17.447286+00:00/task_id=data_storage_task/attempt=1.log
[2025-03-09T11:23:13.895+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T11:21:17.447286+00:00/task_id=data_transformation_task/attempt=1.log
[2025-03-09T11:23:13.895+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_processor_manager/dag_processor_manager.log
[2025-03-09T11:23:13.895+0000] {subprocess.py:93} INFO - 	modified:   logs/data_storage.log
[2025-03-09T11:23:13.895+0000] {subprocess.py:93} INFO - 	modified:   logs/scheduler/2025-03-09/customer_churn.py.log
[2025-03-09T11:23:13.895+0000] {subprocess.py:93} INFO - 
[2025-03-09T11:23:13.896+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-09T11:23:13.896+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-09T11:23:13.896+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/online_store.db
[2025-03-09T11:23:13.896+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/registry.db
[2025-03-09T11:23:13.896+0000] {subprocess.py:93} INFO - 	mlruns/mlruns/
[2025-03-09T11:23:13.897+0000] {subprocess.py:93} INFO - 	models/
[2025-03-09T11:23:13.897+0000] {subprocess.py:93} INFO - 	online.db
[2025-03-09T11:23:13.897+0000] {subprocess.py:93} INFO - 
[2025-03-09T11:23:13.995+0000] {subprocess.py:93} INFO - [main c50a635] Updated stored data version
[2025-03-09T11:23:13.995+0000] {subprocess.py:93} INFO -  5 files changed, 88 insertions(+)
[2025-03-09T11:23:13.995+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T11:21:17.447286+00:00/task_id=data_storage_task/attempt=1.log
[2025-03-09T11:23:19.571+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-09T11:23:21.568+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-09T11:23:21.568+0000] {subprocess.py:93} INFO -    9234802..c50a635  main -> main
[2025-03-09T11:23:21.573+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-09T11:23:21.615+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_storage_task, execution_date=20250309T112117, start_date=20250309T112301, end_date=20250309T112321
[2025-03-09T11:23:21.669+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-09T11:23:21.709+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
