[2025-02-28T04:50:00.450+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-02-28T04:49:39.209814+00:00 [queued]>
[2025-02-28T04:50:00.469+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-02-28T04:49:39.209814+00:00 [queued]>
[2025-02-28T04:50:00.470+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-28T04:50:00.509+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_validation_task> on 2025-02-28 04:49:39.209814+00:00
[2025-02-28T04:50:00.517+0000] {standard_task_runner.py:57} INFO - Started process 8763 to run task
[2025-02-28T04:50:00.522+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_validation_task', 'manual__2025-02-28T04:49:39.209814+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpg5am5wp5']
[2025-02-28T04:50:00.526+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask data_validation_task
[2025-02-28T04:50:00.568+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T04:50:00.660+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-02-28T04:49:39.209814+00:00 [running]> on host 4470298645d8
[2025-02-28T04:50:00.889+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_validation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T04:49:39.209814+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-28T04:49:39.209814+00:00'
[2025-02-28T04:50:00.891+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-28T04:50:00.893+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n                        dvc pull /opt/***/data/raw\n                        python /opt/***/executables/data_validation.py &&                         dvc add /opt/***/reports/csv_validation_report.csv &&                         git add /opt/***/reports/csv_validation_report.csv.dvc &&                         git commit -m "Updated validation" &&                         dvc push\n                    ']
[2025-02-28T04:50:00.909+0000] {subprocess.py:86} INFO - Output:
[2025-02-28T04:50:02.460+0000] {subprocess.py:93} INFO - ERROR: you are not inside of a DVC repository (checked up to mount point '/')
[2025-02-28T04:50:02.892+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/executables/data_validation.py': [Errno 2] No such file or directory
[2025-02-28T04:50:02.898+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-02-28T04:50:02.932+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-02-28T04:50:02.941+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=customer_churn_ml_pipeline, task_id=data_validation_task, execution_date=20250228T044939, start_date=20250228T045000, end_date=20250228T045002
[2025-02-28T04:50:02.969+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 41 for task data_validation_task (Bash command failed. The command returned a non-zero exit code 2.; 8763)
[2025-02-28T04:50:02.986+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-28T04:50:03.062+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
