[2025-03-02T11:37:20.705+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.feature_store_task manual__2025-03-02T11:35:21.762130+00:00 [queued]>
[2025-03-02T11:37:20.728+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.feature_store_task manual__2025-03-02T11:35:21.762130+00:00 [queued]>
[2025-03-02T11:37:20.729+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-02T11:37:20.762+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): feature_store_task> on 2025-03-02 11:35:21.762130+00:00
[2025-03-02T11:37:20.768+0000] {standard_task_runner.py:57} INFO - Started process 16205 to run task
[2025-03-02T11:37:20.774+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'feature_store_task', 'manual__2025-03-02T11:35:21.762130+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpu0cqh2ma']
[2025-03-02T11:37:20.778+0000] {standard_task_runner.py:85} INFO - Job 230: Subtask feature_store_task
[2025-03-02T11:37:20.817+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T11:37:20.897+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.feature_store_task manual__2025-03-02T11:35:21.762130+00:00 [running]> on host 9113a5746a05
[2025-03-02T11:37:21.155+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='feature_store_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T11:35:21.762130+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T11:35:21.762130+00:00'
[2025-03-02T11:37:21.158+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-02T11:37:21.160+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/***/customer_churn_stats/feature_repo &&                         feast apply &&                         feast materialize-incremental $(date -u +\'%Y-%m-%dT%H:%M:%S\') && \t\t\tgit add /opt/***/customer_churn_stats &&       \t\t\tgit add /opt/***/logs\n   \t\t\tgit status &&                         git commit -m "Updated feature store" -a &&                         git push\n                    ']
[2025-03-02T11:37:21.185+0000] {subprocess.py:86} INFO - Output:
[2025-03-02T11:37:28.789+0000] {subprocess.py:93} INFO - 2025-03-02 11:37:28,789 : INFO : Connecting to Database
[2025-03-02T11:37:28.815+0000] {subprocess.py:93} INFO - 2025-03-02 11:37:28,815 : INFO : Connecting to Database Successfull
[2025-03-02T11:37:28.816+0000] {subprocess.py:93} INFO - 2025-03-02 11:37:28,815 : INFO : Reading data from database.
[2025-03-02T11:37:38.320+0000] {subprocess.py:93} INFO - /opt/***/customer_churn_stats/feature_repo/feature_store.py:36: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-03-02T11:37:38.322+0000] {subprocess.py:93} INFO -   data = pd.read_sql(query, connection)
[2025-03-02T11:37:38.322+0000] {subprocess.py:93} INFO - 2025-03-02 11:37:38,320 : INFO : Data collection from database successfull!!
[2025-03-02T11:37:38.322+0000] {subprocess.py:93} INFO - 2025-03-02 11:37:38,320 : INFO : Declaring an entity for the dataset
[2025-03-02T11:37:38.322+0000] {subprocess.py:93} INFO - 2025-03-02 11:37:38,320 : INFO : Declaring the source for raw feature data
[2025-03-02T11:37:38.323+0000] {subprocess.py:93} INFO - 2025-03-02 11:37:38,323 : INFO : Defining the features in a feature view
[2025-03-02T11:37:38.327+0000] {subprocess.py:93} INFO - 2025-03-02 11:37:38,327 : INFO : Feature view creation successfull!!
[2025-03-02T11:37:38.358+0000] {subprocess.py:93} INFO - No changes to registry
[2025-03-02T11:37:38.359+0000] {subprocess.py:93} INFO - No changes to infrastructure
[2025-03-02T11:37:51.484+0000] {subprocess.py:93} INFO - Materializing [1m[32m1[0m feature views to [1m[32m2025-03-02 11:37:39+00:00[0m into the [1m[32msqlite[0m online store.
[2025-03-02T11:37:51.484+0000] {subprocess.py:93} INFO - 
[2025-03-02T11:37:51.485+0000] {subprocess.py:93} INFO - [1m[32mcustomer_stats_fv[0m from [1m[32m2025-03-02 11:07:56+00:00[0m to [1m[32m2025-03-02 11:37:39+00:00[0m:
[2025-03-02T11:37:52.232+0000] {subprocess.py:93} INFO -   0%|                                                                     | 0/10000 [00:00<?, ?it/s]  0%|                                                                     | 0/10000 [00:00<?, ?it/s]
[2025-03-02T11:37:52.475+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-03-02T11:37:52.475+0000] {subprocess.py:93} INFO -   File "/home/***/.local/bin/feast", line 8, in <module>
[2025-03-02T11:37:52.476+0000] {subprocess.py:93} INFO -     sys.exit(cli())
[2025-03-02T11:37:52.476+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
[2025-03-02T11:37:52.476+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2025-03-02T11:37:52.476+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
[2025-03-02T11:37:52.477+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2025-03-02T11:37:52.477+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
[2025-03-02T11:37:52.477+0000] {subprocess.py:93} INFO -     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2025-03-02T11:37:52.477+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
[2025-03-02T11:37:52.478+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2025-03-02T11:37:52.478+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
[2025-03-02T11:37:52.478+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2025-03-02T11:37:52.479+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
[2025-03-02T11:37:52.479+0000] {subprocess.py:93} INFO -     return f(get_current_context(), *args, **kwargs)
[2025-03-02T11:37:52.479+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/feast/cli.py", line 573, in materialize_incremental_command
[2025-03-02T11:37:52.480+0000] {subprocess.py:93} INFO -     store.materialize_incremental(
[2025-03-02T11:37:52.480+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/feast/usage.py", line 288, in wrapper
[2025-03-02T11:37:52.480+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-03-02T11:37:52.480+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/feast/feature_store.py", line 1324, in materialize_incremental
[2025-03-02T11:37:52.481+0000] {subprocess.py:93} INFO -     provider.materialize_single_feature_view(
[2025-03-02T11:37:52.481+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/feast/infra/passthrough_provider.py", line 254, in materialize_single_feature_view
[2025-03-02T11:37:52.481+0000] {subprocess.py:93} INFO -     raise e
[2025-03-02T11:37:52.482+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/feast/infra/materialization/local_engine.py", line 173, in _materialize_one
[2025-03-02T11:37:52.482+0000] {subprocess.py:93} INFO -     self.online_store.online_write_batch(
[2025-03-02T11:37:52.482+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/feast/usage.py", line 299, in wrapper
[2025-03-02T11:37:52.482+0000] {subprocess.py:93} INFO -     raise exc.with_traceback(traceback)
[2025-03-02T11:37:52.482+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/feast/usage.py", line 288, in wrapper
[2025-03-02T11:37:52.483+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-03-02T11:37:52.483+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/feast/infra/online_stores/sqlite.py", line 105, in online_write_batch
[2025-03-02T11:37:52.483+0000] {subprocess.py:93} INFO -     conn.execute(
[2025-03-02T11:37:52.483+0000] {subprocess.py:93} INFO - sqlite3.OperationalError: no such table: customer_churn_stats_customer_stats_fv
[2025-03-02T11:37:53.140+0000] {subprocess.py:93} INFO - On branch main
[2025-03-02T11:37:53.141+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-02T11:37:53.141+0000] {subprocess.py:93} INFO - 
[2025-03-02T11:37:53.142+0000] {subprocess.py:93} INFO - Changes not staged for commit:
[2025-03-02T11:37:53.142+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to update what will be committed)
[2025-03-02T11:37:53.142+0000] {subprocess.py:93} INFO -   (use "git restore <file>..." to discard changes in working directory)
[2025-03-02T11:37:53.143+0000] {subprocess.py:93} INFO - 	modified:   ../../logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T11:35:21.762130+00:00/task_id=data_storage_task/attempt=1.log
[2025-03-02T11:37:53.143+0000] {subprocess.py:93} INFO - 	modified:   ../../logs/feature_store.log
[2025-03-02T11:37:53.143+0000] {subprocess.py:93} INFO - 	modified:   ../../logs/scheduler/2025-03-02/customer_churn.py.log
[2025-03-02T11:37:53.144+0000] {subprocess.py:93} INFO - 
[2025-03-02T11:37:53.144+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-02T11:37:53.144+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-02T11:37:53.144+0000] {subprocess.py:93} INFO - 	data/
[2025-03-02T11:37:53.145+0000] {subprocess.py:93} INFO - 	../../logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T11:35:21.762130+00:00/task_id=feature_store_task/
[2025-03-02T11:37:53.145+0000] {subprocess.py:93} INFO - 
[2025-03-02T11:37:53.145+0000] {subprocess.py:93} INFO - no changes added to commit (use "git add" and/or "git commit -a")
[2025-03-02T11:37:53.200+0000] {subprocess.py:93} INFO - [main 4e1c896] Updated feature store
[2025-03-02T11:37:53.201+0000] {subprocess.py:93} INFO -  3 files changed, 25 insertions(+)
[2025-03-02T11:37:54.709+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-02T11:37:54.710+0000] {subprocess.py:93} INFO -    a5a5617..4e1c896  main -> main
[2025-03-02T11:37:54.718+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-02T11:37:54.824+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=feature_store_task, execution_date=20250302T113521, start_date=20250302T113720, end_date=20250302T113754
[2025-03-02T11:37:54.892+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-02T11:37:54.918+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
