[2025-03-03T17:07:24.743+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_transformation_task manual__2025-03-03T17:06:22.394275+00:00 [queued]>
[2025-03-03T17:07:24.755+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_transformation_task manual__2025-03-03T17:06:22.394275+00:00 [queued]>
[2025-03-03T17:07:24.756+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-03T17:07:24.777+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_transformation_task> on 2025-03-03 17:06:22.394275+00:00
[2025-03-03T17:07:24.782+0000] {standard_task_runner.py:57} INFO - Started process 7205 to run task
[2025-03-03T17:07:24.785+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_transformation_task', 'manual__2025-03-03T17:06:22.394275+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpc0jz_oct']
[2025-03-03T17:07:24.788+0000] {standard_task_runner.py:85} INFO - Job 140: Subtask data_transformation_task
[2025-03-03T17:07:24.809+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T17:07:24.855+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_transformation_task manual__2025-03-03T17:06:22.394275+00:00 [running]> on host 157237bff8f7
[2025-03-03T17:07:24.968+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_transformation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T17:06:22.394275+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T17:06:22.394275+00:00'
[2025-03-03T17:07:24.969+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T17:07:24.970+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/*** &&                        dvc pull /opt/***/data/cleaned\n                        python /opt/***/executables/data_transformation.py &&                         dvc add /opt/***/data/transformed &&                         git add /opt/***/data/transformed.dvc && \t\t\tgit add logs &&    \t\t\tgit status &&                         git commit -m "Updated transformed data version" -a &&                         dvc push && git push\n                    ']
[2025-03-03T17:07:24.979+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T17:07:28.063+0000] {subprocess.py:93} INFO - M       data/cleaned/
[2025-03-03T17:07:28.067+0000] {subprocess.py:93} INFO - 1 file modified
[2025-03-03T17:07:31.319+0000] {subprocess.py:93} INFO - 2025-03-03 17:07:31,319 : INFO : Starting data transformation for csv.
[2025-03-03T17:07:31.320+0000] {subprocess.py:93} INFO - 2025-03-03 17:07:31,320 : ERROR : Failed data transformation: [Errno 2] No such file or directory: '/opt/***/data/cleaned/fintech1/03-03-2025/csv/customer_data.csv'
[2025-03-03T17:07:31.321+0000] {subprocess.py:93} INFO - 2025-03-03 17:07:31,320 : INFO : Starting data transformation for csv.
[2025-03-03T17:07:31.321+0000] {subprocess.py:93} INFO - 2025-03-03 17:07:31,320 : ERROR : Failed data transformation: [Errno 2] No such file or directory: '/opt/***/data/cleaned/fintech2/03-03-2025/database/database_data.csv'
[2025-03-03T17:07:34.329+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:07:34.330+0000] {subprocess.py:93} INFO - To track the changes with git, run:
[2025-03-03T17:07:34.330+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:07:34.331+0000] {subprocess.py:93} INFO - 	git add data/transformed.dvc
[2025-03-03T17:07:34.331+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:07:34.332+0000] {subprocess.py:93} INFO - To enable auto staging, run:
[2025-03-03T17:07:34.333+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:07:34.333+0000] {subprocess.py:93} INFO - 	dvc config core.autostage true
[2025-03-03T17:07:34.781+0000] {subprocess.py:93} INFO - On branch main
[2025-03-03T17:07:34.782+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-03T17:07:34.782+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:07:34.783+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-03T17:07:34.783+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-03T17:07:34.783+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T17:06:22.394275+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-03T17:07:34.784+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T17:06:22.394275+00:00/task_id=data_transformation_task/attempt=1.log
[2025-03-03T17:07:34.784+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_processor_manager/dag_processor_manager.log
[2025-03-03T17:07:34.784+0000] {subprocess.py:93} INFO - 	modified:   logs/data_transformation.log
[2025-03-03T17:07:34.785+0000] {subprocess.py:93} INFO - 	modified:   logs/scheduler/2025-03-03/customer_churn.py.log
[2025-03-03T17:07:34.785+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:07:34.785+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-03T17:07:34.786+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-03T17:07:34.786+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/online_store.db
[2025-03-03T17:07:34.786+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/registry.db
[2025-03-03T17:07:34.787+0000] {subprocess.py:93} INFO - 	models/
[2025-03-03T17:07:34.787+0000] {subprocess.py:93} INFO - 	online.db
[2025-03-03T17:07:34.787+0000] {subprocess.py:93} INFO - 
