[2025-03-01T10:35:13.691+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-01T10:34:53.844242+00:00 [queued]>
[2025-03-01T10:35:13.705+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-01T10:34:53.844242+00:00 [queued]>
[2025-03-01T10:35:13.705+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-01T10:35:13.725+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_validation_task> on 2025-03-01 10:34:53.844242+00:00
[2025-03-01T10:35:13.730+0000] {standard_task_runner.py:57} INFO - Started process 11133 to run task
[2025-03-01T10:35:13.734+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_validation_task', 'manual__2025-03-01T10:34:53.844242+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpaoytkq1l']
[2025-03-01T10:35:13.737+0000] {standard_task_runner.py:85} INFO - Job 91: Subtask data_validation_task
[2025-03-01T10:35:13.763+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-01T10:35:13.820+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-01T10:34:53.844242+00:00 [running]> on host 7e994a0ed489
[2025-03-01T10:35:13.972+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_validation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T10:34:53.844242+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-01T10:34:53.844242+00:00'
[2025-03-01T10:35:13.973+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-01T10:35:13.974+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/***\n                        dvc pull /opt/***/data/raw\n                        python /opt/***/executables/data_validation.py && \t\t\tgit add logs &&                        git commit -m "Updated validation" -a &&                         dvc push && git push\n                    ']
[2025-03-01T10:35:13.986+0000] {subprocess.py:86} INFO - Output:
[2025-03-01T10:35:18.763+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-01T10:35:20.303+0000] {subprocess.py:93} INFO - 2025-03-01 10:35:20,303 : INFO : Starting data validation
[2025-03-01T10:35:20.326+0000] {subprocess.py:93} INFO - 2025-03-01 10:35:20,326 : INFO : Running validation on data received from S3
[2025-03-01T10:35:20.447+0000] {subprocess.py:93} INFO - 2025-03-01 10:35:20,446 : INFO : Saving metrics to S3
[2025-03-01T10:35:20.449+0000] {subprocess.py:93} INFO - 2025-03-01 10:35:20,449 : INFO : Metrics saved to: csv_validation_report.csv
