[2025-03-03T23:30:22.779+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-03T23:29:56.597639+00:00 [queued]>
[2025-03-03T23:30:22.789+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-03T23:29:56.597639+00:00 [queued]>
[2025-03-03T23:30:22.790+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-03T23:30:22.807+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_validation_task> on 2025-03-03 23:29:56.597639+00:00
[2025-03-03T23:30:22.811+0000] {standard_task_runner.py:57} INFO - Started process 6865 to run task
[2025-03-03T23:30:22.815+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_validation_task', 'manual__2025-03-03T23:29:56.597639+00:00', '--job-id', '240', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmploa0c33u']
[2025-03-03T23:30:22.818+0000] {standard_task_runner.py:85} INFO - Job 240: Subtask data_validation_task
[2025-03-03T23:30:22.841+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T23:30:22.886+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-03T23:29:56.597639+00:00 [running]> on host 157237bff8f7
[2025-03-03T23:30:23.002+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_validation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T23:29:56.597639+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T23:29:56.597639+00:00'
[2025-03-03T23:30:23.003+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T23:30:23.004+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/*** &&                        dvc pull /opt/***/data/raw\n                        python /opt/***/executables/data_validation.py && \t\t\tgit add logs && \\   \n\t\t\tgit add reports &&    \t\t\tgit status &&                         git commit -m "Updated validation" -a &&                         dvc push && git push\n                    ']
[2025-03-03T23:30:23.013+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T23:30:26.806+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-03T23:30:28.945+0000] {subprocess.py:93} INFO - 2025-03-03 23:30:28,944 : INFO : Starting data validation for customer_data.csv
[2025-03-03T23:30:28.983+0000] {subprocess.py:93} INFO - 2025-03-03 23:30:28,982 : INFO : Running validation on data received from S3
[2025-03-03T23:30:29.080+0000] {subprocess.py:93} INFO - 2025-03-03 23:30:29,080 : INFO : Saving metrics to S3
[2025-03-03T23:30:29.083+0000] {subprocess.py:93} INFO - 2025-03-03 23:30:29,083 : INFO : Metrics saved to: validation_report.csv
[2025-03-03T23:30:29.084+0000] {subprocess.py:93} INFO - 2025-03-03 23:30:29,083 : INFO : Starting data validation for database_data.csv
[2025-03-03T23:30:29.122+0000] {subprocess.py:93} INFO - 2025-03-03 23:30:29,122 : INFO : Running validation on data received from S3
[2025-03-03T23:30:29.186+0000] {subprocess.py:93} INFO - 2025-03-03 23:30:29,186 : INFO : Saving metrics to S3
[2025-03-03T23:30:29.188+0000] {subprocess.py:93} INFO - 2025-03-03 23:30:29,188 : INFO : Metrics saved to: validation_report.csv
[2025-03-03T23:30:29.324+0000] {subprocess.py:93} INFO - /bin/bash: line 3:  : command not found
[2025-03-03T23:30:29.379+0000] {subprocess.py:93} INFO - On branch main
[2025-03-03T23:30:29.380+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-03T23:30:29.380+0000] {subprocess.py:93} INFO - 
[2025-03-03T23:30:29.380+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-03T23:30:29.381+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-03T23:30:29.381+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T23:29:56.597639+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-03T23:30:29.381+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T23:29:56.597639+00:00/task_id=raw_data_storage_task/attempt=1.log
[2025-03-03T23:30:29.382+0000] {subprocess.py:93} INFO - 	modified:   logs/data_validation.log
[2025-03-03T23:30:29.382+0000] {subprocess.py:93} INFO - 
[2025-03-03T23:30:29.382+0000] {subprocess.py:93} INFO - Changes not staged for commit:
[2025-03-03T23:30:29.383+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to update what will be committed)
[2025-03-03T23:30:29.383+0000] {subprocess.py:93} INFO -   (use "git restore <file>..." to discard changes in working directory)
[2025-03-03T23:30:29.383+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T23:29:56.597639+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-03T23:30:29.384+0000] {subprocess.py:93} INFO - 
[2025-03-03T23:30:29.384+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-03T23:30:29.384+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-03T23:30:29.385+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/online_store.db
[2025-03-03T23:30:29.385+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/registry.db
[2025-03-03T23:30:29.385+0000] {subprocess.py:93} INFO - 	models/
[2025-03-03T23:30:29.386+0000] {subprocess.py:93} INFO - 	online.db
[2025-03-03T23:30:29.386+0000] {subprocess.py:93} INFO - 
[2025-03-03T23:30:29.410+0000] {subprocess.py:93} INFO - [main 735c27a] Updated validation
[2025-03-03T23:30:29.411+0000] {subprocess.py:93} INFO -  3 files changed, 62 insertions(+)
[2025-03-03T23:30:29.411+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T23:29:56.597639+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-03T23:30:34.955+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-03T23:30:36.627+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-03T23:30:36.628+0000] {subprocess.py:93} INFO -    842b14c..735c27a  main -> main
[2025-03-03T23:30:36.637+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-03T23:30:36.683+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_validation_task, execution_date=20250303T232956, start_date=20250303T233022, end_date=20250303T233036
[2025-03-03T23:30:36.735+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-03T23:30:36.787+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
