[2025-03-03T17:16:09.170+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-03T17:15:40.663621+00:00 [queued]>
[2025-03-03T17:16:09.182+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-03T17:15:40.663621+00:00 [queued]>
[2025-03-03T17:16:09.182+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-03T17:16:09.200+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_validation_task> on 2025-03-03 17:15:40.663621+00:00
[2025-03-03T17:16:09.205+0000] {standard_task_runner.py:57} INFO - Started process 8148 to run task
[2025-03-03T17:16:09.209+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_validation_task', 'manual__2025-03-03T17:15:40.663621+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmp5lhdokw_']
[2025-03-03T17:16:09.212+0000] {standard_task_runner.py:85} INFO - Job 154: Subtask data_validation_task
[2025-03-03T17:16:09.235+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T17:16:09.284+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-03T17:15:40.663621+00:00 [running]> on host 157237bff8f7
[2025-03-03T17:16:09.410+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_validation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T17:15:40.663621+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T17:15:40.663621+00:00'
[2025-03-03T17:16:09.411+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T17:16:09.412+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/*** &&                        dvc pull /opt/***/data/raw\n                        python /opt/***/executables/data_validation.py && \t\t\tgit add logs && \\   \n\t\t\tgit add reports &&    \t\t\tgit status &&                         git commit -m "Updated validation" -a &&                         dvc push && git push\n                    ']
[2025-03-03T17:16:09.423+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T17:16:13.053+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-03T17:16:14.417+0000] {subprocess.py:93} INFO - 2025-03-03 17:16:14,416 : INFO : Starting data validation for customer_data.csv
[2025-03-03T17:16:14.444+0000] {subprocess.py:93} INFO - 2025-03-03 17:16:14,444 : INFO : Running validation on data received from S3
[2025-03-03T17:16:14.496+0000] {subprocess.py:93} INFO - 2025-03-03 17:16:14,496 : INFO : Saving metrics to S3
[2025-03-03T17:16:14.499+0000] {subprocess.py:93} INFO - 2025-03-03 17:16:14,498 : ERROR : Error validating  data: Cannot save file into a non-existent directory: 'reports/fintech1/03-03-2025/csv'
[2025-03-03T17:16:14.499+0000] {subprocess.py:93} INFO - 2025-03-03 17:16:14,499 : INFO : Starting data validation for database_data.csv
[2025-03-03T17:16:14.500+0000] {subprocess.py:93} INFO - 2025-03-03 17:16:14,499 : ERROR : Error validating  data: [Errno 2] No such file or directory: '/opt/***/data/raw/fintech2/03-03-2025/database/database_data.csv'
[2025-03-03T17:16:14.608+0000] {subprocess.py:93} INFO - /bin/bash: line 3:  : command not found
[2025-03-03T17:16:14.639+0000] {subprocess.py:93} INFO - On branch main
[2025-03-03T17:16:14.640+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-03T17:16:14.640+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:16:14.640+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-03T17:16:14.640+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-03T17:16:14.641+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T17:15:40.663621+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-03T17:16:14.641+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T17:15:40.663621+00:00/task_id=raw_data_storage_task/attempt=1.log
[2025-03-03T17:16:14.641+0000] {subprocess.py:93} INFO - 	modified:   logs/data_validation.log
[2025-03-03T17:16:14.642+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:16:14.642+0000] {subprocess.py:93} INFO - Changes not staged for commit:
[2025-03-03T17:16:14.642+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to update what will be committed)
[2025-03-03T17:16:14.642+0000] {subprocess.py:93} INFO -   (use "git restore <file>..." to discard changes in working directory)
[2025-03-03T17:16:14.643+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T17:15:40.663621+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-03T17:16:14.643+0000] {subprocess.py:93} INFO - 
[2025-03-03T17:16:14.643+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-03T17:16:14.644+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-03T17:16:14.644+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/online_store.db
[2025-03-03T17:16:14.644+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/registry.db
[2025-03-03T17:16:14.644+0000] {subprocess.py:93} INFO - 	models/
[2025-03-03T17:16:14.645+0000] {subprocess.py:93} INFO - 	online.db
[2025-03-03T17:16:14.645+0000] {subprocess.py:93} INFO - 
