[2025-03-02T08:00:47.836+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_storage_task scheduled__2025-03-01T08:00:00+00:00 [queued]>
[2025-03-02T08:00:47.904+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_storage_task scheduled__2025-03-01T08:00:00+00:00 [queued]>
[2025-03-02T08:00:47.905+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-02T08:00:48.239+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_storage_task> on 2025-03-01 08:00:00+00:00
[2025-03-02T08:00:48.261+0000] {standard_task_runner.py:57} INFO - Started process 7826 to run task
[2025-03-02T08:00:48.296+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_storage_task', 'scheduled__2025-03-01T08:00:00+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpsaunlepm']
[2025-03-02T08:00:48.329+0000] {standard_task_runner.py:85} INFO - Job 295: Subtask data_storage_task
[2025-03-02T08:00:48.639+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T08:00:49.020+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_storage_task scheduled__2025-03-01T08:00:00+00:00 [running]> on host 7e994a0ed489
[2025-03-02T08:00:49.845+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_storage_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-01T08:00:00+00:00'
[2025-03-02T08:00:49.861+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-02T08:00:49.892+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tNOW=$(date \'+%d-%m-%Y\') &&\t\t\tcd /opt/***\n                        dvc pull /opt/***/data/transformed\n                        python /opt/***/executables/data_storage.py && \t\t\tgit add logs &&                        git commit -m "Updated stored data version" -a &&                         dvc push && git push\n                    ']
[2025-03-02T08:00:49.960+0000] {subprocess.py:86} INFO - Output:
[2025-03-02T08:01:04.929+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-02T08:01:16.067+0000] {subprocess.py:93} INFO - 2025-03-02 08:01:16,066 : ERROR : Error storing data: [Errno 2] No such file or directory: 'settings.json'
