[2025-03-09T17:13:16.232+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-09T17:12:32.664464+00:00 [queued]>
[2025-03-09T17:13:16.257+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-09T17:12:32.664464+00:00 [queued]>
[2025-03-09T17:13:16.257+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-09T17:13:16.290+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_validation_task> on 2025-03-09 17:12:32.664464+00:00
[2025-03-09T17:13:16.297+0000] {standard_task_runner.py:57} INFO - Started process 12244 to run task
[2025-03-09T17:13:16.303+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_validation_task', 'manual__2025-03-09T17:12:32.664464+00:00', '--job-id', '406', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpnkaxyu06']
[2025-03-09T17:13:16.307+0000] {standard_task_runner.py:85} INFO - Job 406: Subtask data_validation_task
[2025-03-09T17:13:16.352+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-09T17:13:16.455+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_validation_task manual__2025-03-09T17:12:32.664464+00:00 [running]> on host 157237bff8f7
[2025-03-09T17:13:16.679+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_validation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T17:12:32.664464+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T17:12:32.664464+00:00'
[2025-03-09T17:13:16.681+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-09T17:13:16.683+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/*** &&                        dvc pull /opt/***/data/raw\n                        python /opt/***/executables/data_validation.py && \t\t\tgit add logs && \\   \n\t\t\tgit add reports &&    \t\t\tgit status &&                         git commit -m "Updated validation" -a &&                         dvc push && git push\n                    ']
[2025-03-09T17:13:16.699+0000] {subprocess.py:86} INFO - Output:
[2025-03-09T17:13:22.156+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-09T17:13:24.610+0000] {subprocess.py:93} INFO - 2025-03-09 17:13:24,610 : INFO : Starting data validation for customer_data.csv
[2025-03-09T17:13:24.653+0000] {subprocess.py:93} INFO - 2025-03-09 17:13:24,653 : INFO : Running validation on data received from S3
[2025-03-09T17:13:24.769+0000] {subprocess.py:93} INFO - 2025-03-09 17:13:24,769 : INFO : Saving metrics to S3
[2025-03-09T17:13:24.774+0000] {subprocess.py:93} INFO - 2025-03-09 17:13:24,773 : INFO : Metrics saved to: validation_report.csv
[2025-03-09T17:13:24.774+0000] {subprocess.py:93} INFO - 2025-03-09 17:13:24,774 : INFO : Starting data validation for database_data.csv
[2025-03-09T17:13:24.814+0000] {subprocess.py:93} INFO - 2025-03-09 17:13:24,814 : INFO : Running validation on data received from S3
[2025-03-09T17:13:24.921+0000] {subprocess.py:93} INFO - 2025-03-09 17:13:24,921 : INFO : Saving metrics to S3
[2025-03-09T17:13:24.924+0000] {subprocess.py:93} INFO - 2025-03-09 17:13:24,924 : INFO : Metrics saved to: validation_report.csv
[2025-03-09T17:13:25.120+0000] {subprocess.py:93} INFO - /bin/bash: line 3:  : command not found
[2025-03-09T17:13:25.174+0000] {subprocess.py:93} INFO - On branch main
[2025-03-09T17:13:25.175+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-09T17:13:25.175+0000] {subprocess.py:93} INFO - 
[2025-03-09T17:13:25.176+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-09T17:13:25.176+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-09T17:13:25.177+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T17:12:32.664464+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-09T17:13:25.177+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T17:12:32.664464+00:00/task_id=raw_data_storage_task/attempt=1.log
[2025-03-09T17:13:25.178+0000] {subprocess.py:93} INFO - 	modified:   logs/data_validation.log
[2025-03-09T17:13:25.178+0000] {subprocess.py:93} INFO - 
[2025-03-09T17:13:25.179+0000] {subprocess.py:93} INFO - Changes not staged for commit:
[2025-03-09T17:13:25.179+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to update what will be committed)
[2025-03-09T17:13:25.179+0000] {subprocess.py:93} INFO -   (use "git restore <file>..." to discard changes in working directory)
[2025-03-09T17:13:25.180+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T17:12:32.664464+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-09T17:13:25.180+0000] {subprocess.py:93} INFO - 
[2025-03-09T17:13:25.183+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-09T17:13:25.184+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-09T17:13:25.185+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/online_store.db
[2025-03-09T17:13:25.186+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/registry.db
[2025-03-09T17:13:25.187+0000] {subprocess.py:93} INFO - 	mlartifacts/
[2025-03-09T17:13:25.188+0000] {subprocess.py:93} INFO - 	online.db
[2025-03-09T17:13:25.188+0000] {subprocess.py:93} INFO - 
[2025-03-09T17:13:25.217+0000] {subprocess.py:93} INFO - [main c08cc64] Updated validation
[2025-03-09T17:13:25.218+0000] {subprocess.py:93} INFO -  3 files changed, 62 insertions(+)
[2025-03-09T17:13:25.218+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-09T17:12:32.664464+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-09T17:13:32.422+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-09T17:13:34.282+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-09T17:13:34.283+0000] {subprocess.py:93} INFO -    e4f9121..c08cc64  main -> main
[2025-03-09T17:13:34.289+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-09T17:13:34.344+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_validation_task, execution_date=20250309T171232, start_date=20250309T171316, end_date=20250309T171334
[2025-03-09T17:13:34.390+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-09T17:13:34.448+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
