[2025-03-02T10:03:16.334+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-02T10:02:37.910958+00:00 [queued]>
[2025-03-02T10:03:16.354+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-02T10:02:37.910958+00:00 [queued]>
[2025-03-02T10:03:16.354+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-02T10:03:16.377+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_preparation_task> on 2025-03-02 10:02:37.910958+00:00
[2025-03-02T10:03:16.382+0000] {standard_task_runner.py:57} INFO - Started process 9370 to run task
[2025-03-02T10:03:16.385+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_preparation_task', 'manual__2025-03-02T10:02:37.910958+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmp31_0lze5']
[2025-03-02T10:03:16.389+0000] {standard_task_runner.py:85} INFO - Job 125: Subtask data_preparation_task
[2025-03-02T10:03:16.414+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T10:03:16.462+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-02T10:02:37.910958+00:00 [running]> on host 9113a5746a05
[2025-03-02T10:03:16.612+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_preparation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T10:02:37.910958+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T10:02:37.910958+00:00'
[2025-03-02T10:03:16.614+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-02T10:03:16.614+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/*** &&\t\t\tpython /opt/***/executables/data_preparation.py &&                         dvc add /opt/***/data/cleaned &&                         git add /opt/***/data/cleaned.dvc && \t\t\tgit add logs && \\   \n\t\t\tgit add visualization &&    \t\t\tgit status &&                         git commit -m "Updated cleaned data version" -a &&                         dvc push && git push\n                    ']
[2025-03-02T10:03:16.625+0000] {subprocess.py:86} INFO - Output:
[2025-03-02T10:03:19.272+0000] {subprocess.py:93} INFO - 2025-03-02 10:03:19,272 : INFO : Starting data preparation for csv.
[2025-03-02T10:03:19.291+0000] {subprocess.py:93} INFO - 2025-03-02 10:03:19,291 : INFO : Handling 'Tenure', 'Balance', 'EstimatedSalary' empty data
[2025-03-02T10:03:19.291+0000] {subprocess.py:93} INFO - 2025-03-02 10:03:19,291 : INFO : Handling 'Age' empty data
[2025-03-02T10:03:19.292+0000] {subprocess.py:93} INFO - 2025-03-02 10:03:19,292 : INFO : Droping 'Surname' as it may lead to profiling, 'RowNumber', 'CustomerId' as it is not required
[2025-03-02T10:03:19.294+0000] {subprocess.py:93} INFO - 2025-03-02 10:03:19,294 : INFO : Making 'Geography', 'Gender', 'HasCrCard', 'IsActiveMember' as categorical
[2025-03-02T10:03:19.301+0000] {subprocess.py:93} INFO - 2025-03-02 10:03:19,301 : INFO : Saving data to S3.
[2025-03-02T10:03:19.302+0000] {subprocess.py:93} INFO - 2025-03-02 10:03:19,302 : ERROR : Error in preparing dataCannot save file into a non-existent directory: '/opt/***/data/cleaned/02-03-2025/csv'
[2025-03-02T10:03:21.350+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:03:21.350+0000] {subprocess.py:93} INFO - To track the changes with git, run:
[2025-03-02T10:03:21.352+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:03:21.352+0000] {subprocess.py:93} INFO - 	git add data/cleaned.dvc
[2025-03-02T10:03:21.352+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:03:21.353+0000] {subprocess.py:93} INFO - To enable auto staging, run:
[2025-03-02T10:03:21.353+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:03:21.353+0000] {subprocess.py:93} INFO - 	dvc config core.autostage true
[2025-03-02T10:03:21.665+0000] {subprocess.py:93} INFO - /bin/bash: line 2:  : command not found
[2025-03-02T10:03:21.689+0000] {subprocess.py:93} INFO - On branch main
[2025-03-02T10:03:21.690+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-02T10:03:21.690+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:03:21.690+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-02T10:03:21.690+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-02T10:03:21.691+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T10:02:37.910958+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-02T10:03:21.691+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T10:02:37.910958+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-02T10:03:21.691+0000] {subprocess.py:93} INFO - 	modified:   logs/data_preparation.log
[2025-03-02T10:03:21.691+0000] {subprocess.py:93} INFO - 	modified:   logs/scheduler/2025-03-02/customer_churn.py.log
[2025-03-02T10:03:21.691+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:03:21.691+0000] {subprocess.py:93} INFO - Changes not staged for commit:
[2025-03-02T10:03:21.692+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to update what will be committed)
[2025-03-02T10:03:21.692+0000] {subprocess.py:93} INFO -   (use "git restore <file>..." to discard changes in working directory)
[2025-03-02T10:03:21.692+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T10:02:37.910958+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-02T10:03:21.693+0000] {subprocess.py:93} INFO - 
[2025-03-02T10:03:21.720+0000] {subprocess.py:93} INFO - [main 34ee2b6] Updated cleaned data version
[2025-03-02T10:03:21.720+0000] {subprocess.py:93} INFO -  4 files changed, 99 insertions(+)
[2025-03-02T10:03:21.720+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T10:02:37.910958+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-02T10:03:21.721+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-02T10:02:37.910958+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-02T10:03:27.025+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-02T10:03:29.020+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-02T10:03:29.021+0000] {subprocess.py:93} INFO -    e12d461..34ee2b6  main -> main
[2025-03-02T10:03:29.035+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-02T10:03:29.098+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_preparation_task, execution_date=20250302T100237, start_date=20250302T100316, end_date=20250302T100329
[2025-03-02T10:03:29.140+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-02T10:03:29.202+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
