[2025-03-02T06:16:15.258+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-02T06:15:20.066703+00:00 [queued]>
[2025-03-02T06:16:15.268+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-02T06:15:20.066703+00:00 [queued]>
[2025-03-02T06:16:15.269+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-02T06:16:15.289+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_preparation_task> on 2025-03-02 06:15:20.066703+00:00
[2025-03-02T06:16:15.293+0000] {standard_task_runner.py:57} INFO - Started process 3159 to run task
[2025-03-02T06:16:15.296+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_preparation_task', 'manual__2025-03-02T06:15:20.066703+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmprs7wvizo']
[2025-03-02T06:16:15.298+0000] {standard_task_runner.py:85} INFO - Job 232: Subtask data_preparation_task
[2025-03-02T06:16:15.319+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T06:16:15.364+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-02T06:15:20.066703+00:00 [running]> on host 7e994a0ed489
[2025-03-02T06:16:15.486+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_preparation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T06:15:20.066703+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T06:15:20.066703+00:00'
[2025-03-02T06:16:15.488+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-02T06:16:15.488+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tNOW=$(date \'+%d-%m-%Y\') &&\t\t\tcd /opt/*** &&\t\t\tpython /opt/***/executables/data_preparation.py &&                         dvc add /opt/***/data/cleaned/$NOW/csv &&                         dvc add /opt/***/data/cleaned/$NOW/database &&                         git add /opt/***/data/cleaned/$NOW/csv.dvc &&                         git add /opt/***/data/cleaned/$NOW/database.dvc && \t\t\tgit add logs &&\\   \n\t\t\tgit add visualization &&                        git commit -m "Updated cleaned data version" -a &&                         dvc push && git push\n                    ']
[2025-03-02T06:16:15.497+0000] {subprocess.py:86} INFO - Output:
[2025-03-02T06:16:18.924+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-03-02T06:16:18.925+0000] {subprocess.py:93} INFO -   File "/opt/***/executables/data_preparation.py", line 11, in <module>
[2025-03-02T06:16:18.925+0000] {subprocess.py:93} INFO -     with open("settings.json", "r") as file:
[2025-03-02T06:16:18.925+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'settings.json'
[2025-03-02T06:16:19.243+0000] {subprocess.py:93} INFO - [main ec2f786] Updated cleaned data version
[2025-03-02T06:16:19.244+0000] {subprocess.py:93} INFO -  2 files changed, 15 insertions(+)
[2025-03-02T06:16:24.664+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-02T06:16:26.573+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-02T06:16:26.574+0000] {subprocess.py:93} INFO -    f3b66a3..ec2f786  main -> main
[2025-03-02T06:16:26.581+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-02T06:16:26.623+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_preparation_task, execution_date=20250302T061520, start_date=20250302T061615, end_date=20250302T061626
[2025-03-02T06:16:26.669+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-02T06:16:26.705+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
