[2025-03-03T16:44:18.747+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-03T16:43:39.817528+00:00 [queued]>
[2025-03-03T16:44:18.760+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-03T16:43:39.817528+00:00 [queued]>
[2025-03-03T16:44:18.760+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-03T16:44:18.779+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_preparation_task> on 2025-03-03 16:43:39.817528+00:00
[2025-03-03T16:44:18.785+0000] {standard_task_runner.py:57} INFO - Started process 5129 to run task
[2025-03-03T16:44:18.789+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_preparation_task', 'manual__2025-03-03T16:43:39.817528+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpv4x2m67p']
[2025-03-03T16:44:18.792+0000] {standard_task_runner.py:85} INFO - Job 112: Subtask data_preparation_task
[2025-03-03T16:44:18.817+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T16:44:18.872+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-03T16:43:39.817528+00:00 [running]> on host 157237bff8f7
[2025-03-03T16:44:19.008+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_preparation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T16:43:39.817528+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T16:43:39.817528+00:00'
[2025-03-03T16:44:19.009+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T16:44:19.010+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/*** &&\t\t\tpython /opt/***/executables/data_preparation.py &&                         dvc add /opt/***/data/cleaned &&                         git add /opt/***/data/cleaned.dvc && \t\t\tgit add logs && \\   \n\t\t\tgit add visualization &&    \t\t\tgit status &&                         git commit -m "Updated cleaned data version" -a &&                         dvc push && git push\n                    ']
[2025-03-03T16:44:19.021+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T16:44:21.922+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:21,922 : INFO : Starting data preparation for customer_data.csv.
[2025-03-03T16:44:21.942+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:21,941 : INFO : Dropping 'Tenure' less than 0 and greater than 110 * 12
[2025-03-03T16:44:21.945+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:21,945 : INFO : Handling 'Age' empty data
[2025-03-03T16:44:21.946+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:21,946 : INFO : Dropping 'Age' less than 18 and greater than 110
[2025-03-03T16:44:21.949+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:21,949 : INFO : Dropping 'Estimated Salary' & 'Credit Score' with 0 & negative values
[2025-03-03T16:44:21.951+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:21,951 : INFO : Handling 'Balance', 'EstimatedSalary' empty data with mean
[2025-03-03T16:44:21.952+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:21,951 : INFO : Droping 'Surname' as it may lead to profiling, 'RowNumber', 'CustomerId' as it is not required
[2025-03-03T16:44:21.953+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:21,953 : INFO : Making 'Geography', 'Gender', 'HasCrCard', 'IsActiveMember' as categorical
[2025-03-03T16:44:21.960+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:21,959 : INFO : Saving data to S3.
[2025-03-03T16:44:21.961+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:21,960 : INFO : Directory created at /opt/***/data/cleaned/fintech1/03-03-2025/csv
[2025-03-03T16:44:22.144+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:22,144 : INFO : Connected to s3
[2025-03-03T16:44:24.931+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:24,930 : INFO : File uploaded to S3
[2025-03-03T16:44:24.933+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:24,933 : ERROR : Error in creating report[Errno 21] Is a directory: '/opt/***/visualization/fintech1/03-03-2025/csv'
[2025-03-03T16:44:24.933+0000] {subprocess.py:93} INFO - 2025-03-03 16:44:24,933 : ERROR : Error in preparing data[Errno 21] Is a directory: '/opt/***/visualization/fintech1/03-03-2025/csv'
[2025-03-03T16:44:24.940+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-03-03T16:44:24.941+0000] {subprocess.py:93} INFO -   File "/opt/***/executables/data_preparation.py", line 148, in <module>
[2025-03-03T16:44:24.941+0000] {subprocess.py:93} INFO -     prepare_data("customer_data.csv", "csv", "fintech1", "customer_data.csv")
[2025-03-03T16:44:24.941+0000] {subprocess.py:93} INFO -   File "/opt/***/executables/data_preparation.py", line 92, in prepare_data
[2025-03-03T16:44:24.942+0000] {subprocess.py:93} INFO -     raise e
[2025-03-03T16:44:24.942+0000] {subprocess.py:93} INFO -   File "/opt/***/executables/data_preparation.py", line 89, in prepare_data
[2025-03-03T16:44:24.942+0000] {subprocess.py:93} INFO -     generate_report(df, source, type)
[2025-03-03T16:44:24.942+0000] {subprocess.py:93} INFO -   File "/opt/***/executables/data_preparation.py", line 144, in generate_report
[2025-03-03T16:44:24.942+0000] {subprocess.py:93} INFO -     raise e
[2025-03-03T16:44:24.943+0000] {subprocess.py:93} INFO -   File "/opt/***/executables/data_preparation.py", line 99, in generate_report
[2025-03-03T16:44:24.943+0000] {subprocess.py:93} INFO -     with PdfPages(file_path) as pdf:
[2025-03-03T16:44:24.943+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 2725, in __init__
[2025-03-03T16:44:24.943+0000] {subprocess.py:93} INFO -     self._file = PdfFile(filename, metadata=metadata)
[2025-03-03T16:44:24.943+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 714, in __init__
[2025-03-03T16:44:24.943+0000] {subprocess.py:93} INFO -     fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)
[2025-03-03T16:44:24.944+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 499, in to_filehandle
[2025-03-03T16:44:24.944+0000] {subprocess.py:93} INFO -     fh = open(fname, flag, encoding=encoding)
[2025-03-03T16:44:24.944+0000] {subprocess.py:93} INFO - IsADirectoryError: [Errno 21] Is a directory: '/opt/***/visualization/fintech1/03-03-2025/csv'
[2025-03-03T16:44:25.343+0000] {subprocess.py:93} INFO - On branch main
[2025-03-03T16:44:25.343+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-03T16:44:25.343+0000] {subprocess.py:93} INFO - 
[2025-03-03T16:44:25.343+0000] {subprocess.py:93} INFO - Changes not staged for commit:
[2025-03-03T16:44:25.344+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to update what will be committed)
[2025-03-03T16:44:25.344+0000] {subprocess.py:93} INFO -   (use "git restore <file>..." to discard changes in working directory)
[2025-03-03T16:44:25.344+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_processor_manager/dag_processor_manager.log
[2025-03-03T16:44:25.344+0000] {subprocess.py:93} INFO - 	modified:   logs/data_preparation.log
[2025-03-03T16:44:25.344+0000] {subprocess.py:93} INFO - 	modified:   logs/scheduler/2025-03-03/customer_churn.py.log
[2025-03-03T16:44:25.344+0000] {subprocess.py:93} INFO - 
[2025-03-03T16:44:25.344+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-03T16:44:25.344+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-03T16:44:25.345+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/online_store.db
[2025-03-03T16:44:25.345+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/registry.db
[2025-03-03T16:44:25.345+0000] {subprocess.py:93} INFO - 	logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T16:43:39.817528+00:00/task_id=data_preparation_task/
[2025-03-03T16:44:25.345+0000] {subprocess.py:93} INFO - 	logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T16:43:39.817528+00:00/task_id=data_validation_task/
[2025-03-03T16:44:25.345+0000] {subprocess.py:93} INFO - 	models/
[2025-03-03T16:44:25.345+0000] {subprocess.py:93} INFO - 	online.db
[2025-03-03T16:44:25.345+0000] {subprocess.py:93} INFO - 
[2025-03-03T16:44:25.345+0000] {subprocess.py:93} INFO - no changes added to commit (use "git add" and/or "git commit -a")
[2025-03-03T16:44:25.420+0000] {subprocess.py:93} INFO - [main 293946d] Updated cleaned data version
[2025-03-03T16:44:25.420+0000] {subprocess.py:93} INFO -  3 files changed, 29 insertions(+)
[2025-03-03T16:44:29.742+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-03T16:44:31.556+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-03T16:44:31.557+0000] {subprocess.py:93} INFO -    ecea439..293946d  main -> main
[2025-03-03T16:44:31.570+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-03T16:44:31.610+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_preparation_task, execution_date=20250303T164339, start_date=20250303T164418, end_date=20250303T164431
[2025-03-03T16:44:31.640+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-03T16:44:31.675+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
